#Macro file for example B4
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Default kinematics: 
# electron 50 MeV in direction (0.,0.,1.)
# 1 event with tracking/verbose
#
/tracking/verbose 0

/gun/particle neutron
/gun/energy 5 MeV
#/gun/time 1000 s
/run/printProgress 1000
/run/beamOn 10000
#
#/process/list
#/process/inactivate eBrem
#
